export enum TipoPuesto {
  OBRAS = 'OBRAS',
  SALAS_DE_VENTA = 'SALAS_DE_VENTA',
  ALMACENES = 'ALMACENES',
  FABRICAS = 'FABRICAS',
  RESTAURANTES = 'RESTAURANTES',
  GRIFOS = 'GRIFOS',
  EDIFICIOS = 'EDIFICIOS',
  EVENTOS = 'EVENTOS',
  SALA = 'SALA'
}
